{{- if .Values.credentialsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitbucketRunnerAutoscaler.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" . | nindent 4 }}
data:
  atlassianAccountEmail: {{ .Values.credentialsSecret.atlassianAccountEmail | b64enc | quote }}
  atlassianApiToken: {{ .Values.credentialsSecret.atlassianApiToken | b64enc | quote }}
  # App password - DEPRECATED
  bitbucketUsername: {{ .Values.credentialsSecret.bitbucketUsername | b64enc | quote }}
  bitbucketAppPassword: {{ .Values.credentialsSecret.bitbucketAppPassword | b64enc | quote }}
{{- end }}
